from typing import Protocol

from app.models import Lesson


class LessonRepository(Protocol):
    async def search(self, query: str, scope: dict[str, str], limit: int) -> list[Lesson]: ...
    async def get(self, lesson_id: str) -> Lesson | None: ...
    async def upsert(self, lesson: Lesson) -> None: ...
    async def list_all(self) -> list[Lesson]: ...


class RunRepository(Protocol):
    async def save_stage(self, run_id: str, stage: str, payload: dict[str, object]) -> None: ...
    async def stages(self, run_id: str) -> list[tuple[str, dict[str, object]]]: ...
